name = "larped-site"
compatibility_date = "2026-01-01"

[pages]
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "larped-db"
database_id = "001cd5aa-304b-4326-9070-a60953ca187f"
