name = "larped"
compatibility_date = "2025-01-01"

# For Cloudflare Pages + Functions, wrangler.toml is mainly used for local dev and bindings.
# Cloudflare Pages will read bindings from the Pages project settings too.

[[d1_databases]]
binding = "DB"
database_name = "larped_db"
database_id = "25ec299e-9d1d-4eaa-b570-1e2330af1cb4"
